export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REDIRECT = 'LOGIN_REDIRECT';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_REDIRECT = 'SIGNUP_REDIRECT';
