export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const SET_FETCHING_USERS_LIMIT = 'SET_FETCHING_USERS_LIMIT';