export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const SET_FETCHING_USERS_LIMIT = 'SET_FETCHING_USERS_LIMIT';